# Generated by Django 5.1.3 on 2024-11-29 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                ("street", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("contact_email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                ("platform_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=15)),
                ("quantity_sold", models.PositiveIntegerField()),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_sale_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("date_of_sale", models.DateField(db_index=True)),
                ("seller_id", models.CharField(db_index=True, max_length=100)),
                ("additional_data", models.JSONField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="sales.customer",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="sales.platform",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="sales.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("order_id", "product")},
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.AutoField(primary_key=True, serialize=False)),
                ("delivery_date", models.DateField(db_index=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("In Transit", "In Transit"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("delivery_partner", models.CharField(max_length=100)),
                (
                    "delivery_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="sales.address",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="sales.order",
                    ),
                ),
            ],
        ),
    ]
