version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - web

  web:
    container_name: ecomapp
    build: .
    command: >
      sh -c "
        python3 manage.py collectstatic --noinput &&
        python3 manage.py migrate --noinput &&
        gunicorn -b 0.0.0.0 -p 8000 ecom_metrics.wsgi:application
        "
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - backend

networks:
  backend:
    driver: bridge
